version: '3'
services:
  node:
    build: .
    tty: true
    container_name: 'react'
    environment:
      - NODE_ENV=development
    volumes:
    - ./:/app
    command: sh -c "cd reactapp && npm start"
    ports:
    - "3000:3000"